package com.github.diegoberaldin.raccoonforlemmy.core_appearance.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF6345CB)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE6DEFF)
val md_theme_light_onPrimaryContainer = Color(0xFF1D0061)
val md_theme_light_secondary = Color(0xFF006780)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFB7EAFF)
val md_theme_light_onSecondaryContainer = Color(0xFF001F28)
val md_theme_light_tertiary = Color(0xFF2E4EDC)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDEE1FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001159)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FDFF)
val md_theme_light_onBackground = Color(0xFF001F25)
val md_theme_light_surface = Color(0xFFF8FDFF)
val md_theme_light_onSurface = Color(0xFF001F25)
val md_theme_light_surfaceVariant = Color(0xFFE6E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF48454E)
val md_theme_light_outline = Color(0xFF79757F)
val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(0xFF00363F)
val md_theme_light_inversePrimary = Color(0xFFCBBEFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF6345CB)
val md_theme_light_outlineVariant = Color(0xFFC9C4D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFCBBEFF)
val md_theme_dark_onPrimary = Color(0xFF330098)
val md_theme_dark_primaryContainer = Color(0xFF4A28B2)
val md_theme_dark_onPrimaryContainer = Color(0xFFE6DEFF)
val md_theme_dark_secondary = Color(0xFF5BD5FC)
val md_theme_dark_onSecondary = Color(0xFF003543)
val md_theme_dark_secondaryContainer = Color(0xFF004E61)
val md_theme_dark_onSecondaryContainer = Color(0xFFB7EAFF)
val md_theme_dark_tertiary = Color(0xFFBAC3FF)
val md_theme_dark_onTertiary = Color(0xFF00218D)
val md_theme_dark_tertiaryContainer = Color(0xFF0031C4)
val md_theme_dark_onTertiaryContainer = Color(0xFFDEE1FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF48454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC9C4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFF6345CB)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFCBBEFF)
val md_theme_dark_outlineVariant = Color(0xFF48454E)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF3A0CA3)
