package com.github.diegoberaldin.raccoonforlemmy.domain_identity.di

import com.github.diegoberaldin.raccoonforlemmy.domain_identity.repository.ApiConfigurationRepository

expect fun getApiConfigurationRepository(): ApiConfigurationRepository