[versions]
androidx_activity_compose = "1.7.2"
androidx_datastore = "1.1.0-dev01"
android_gradle = "7.4.2"
compose = "1.4.3"
koin = "3.2.0"
kotlin = "1.8.20"
moko_resources = "0.23.0"
voyager = "1.0.0-rc05"

[libraries]

androidx_activity_compose = { module = "androidx.activity:activity-compose", version.ref = "androidx.activity.compose" }
androidx_datastore = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx.datastore" }

koin_core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin_test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin_android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

moko_gradle = { module = "dev.icerock.moko:resources-generator", version.ref = "moko.resources" }
moko_resources = { module = "dev.icerock.moko:resources", version.ref = "moko.resources" }
moko_resources_compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko.resources" }
moko_resources_test = { module = "dev.icerock.moko:resources-test", version.ref = "moko.resources" }

voyager_navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager_bottomsheet = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyager" }
voyager_tab = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
voyager_transition = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager_koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }
voyager_androidx = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }

[plugins]

android_application = { id = "com.android.application", version.ref = "android.gradle" }
android_library = { id = "com.android.library", version.ref = "android.gradle" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin_multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version = "1.4.1" }
native_cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
moko_resources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko.resources" }