[versions]
androidx_activity = "1.7.2"
androidx_crypto = "1.0.0"
android_gradle = "7.4.2"
compose = "1.5.1"
crashlytics = "18.4.1"
crashlytics_gradle = "2.9.9"
gms_gradle = "4.3.15"
kamel = "0.7.1"
koin = "3.5.0"
kotlin = "1.8.20"
kotlinx_serialization_json = "1.6.0"
ksp = "1.8.20-1.0.11"
ktor = "2.3.4"
ktorfit_gradle = "1.0.0"
ktorfit_lib = "1.7.0"
markdown = "0.5.0"
moko_resources = "0.23.0"
multiplatform_settings = "1.0.0"
voyager = "1.0.0-rc06"

[libraries]

androidx_activity_compose = { module = "androidx.activity:activity-compose", version.ref = "androidx.activity" }
androidx_activity = { module = "androidx.activity:activity", version.ref = "androidx.activity" }
androidx_security_crypto = { module = "androidx.security:security-crypto", version.ref = "androidx.crypto" }

firebase_crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "crashlytics" }

kamel = { module = "media.kamel:kamel-image", version.ref = "kamel" }
markdown = { module = "org.jetbrains:markdown", version.ref = "markdown" }
multiplatform_settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform.settings" }
kotlinx_serialization_json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx.serialization.json" }

koin_core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin_test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin_android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

ktor_serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor_cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor_contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor_logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor_json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorfit_ksp = { module = "de.jensklingenberg.ktorfit:ktorfit-ksp", version.ref = "ktorfit.lib" }
ktorfit_lib = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit.lib" }

moko_gradle = { module = "dev.icerock.moko:resources-generator", version.ref = "moko.resources" }
moko_resources = { module = "dev.icerock.moko:resources", version.ref = "moko.resources" }
moko_resources_compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko.resources" }
moko_resources_test = { module = "dev.icerock.moko:resources-test", version.ref = "moko.resources" }

voyager_navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager_bottomsheet = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyager" }
voyager_tab = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
voyager_transition = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager_koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }
voyager_androidx = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }

[plugins]

android_application = { id = "com.android.application", version.ref = "android.gradle" }
android_library = { id = "com.android.library", version.ref = "android.gradle" }
compose = { id = "org.jetbrains.compose", version = "1.4.1" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics.gradle" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin_multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit.gradle" }
native_cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
moko_resources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko.resources" }
gms = { id = "com.google.gms.google-services", version.ref = "gms.gradle" }