[versions]

androidx-activity = "1.9.0"
androidx-browser = "1.8.0"
androidx-core = "1.13.1"
androidx-crypto = "1.0.0"
androidx-media3 = "1.3.1"
androidx-splashscreen = "1.0.1"
androidx-work = "2.9.0"
android-gradle = "8.4.1"
coil = "2.6.0"
compose = "1.6.11"
detekt = "1.23.6"
kamel = "0.9.5"
koin = "3.5.6"
kotlin = "2.0.0"
kotlincrypto = "0.5.1"
kotlinx-coroutines = "1.8.1"
kotlinx-serialization-json = "1.6.3"
ksp = "2.0.0-1.0.21"
ktor = "2.3.11"
ktorfit = "2.0.0-rc01"
lyricist = "1.7.0"
materialKolor = "1.6.2"
mockk = "1.13.11"
multiplatform-markdown-renderer = "0.21.0"
multiplatform-settings = "1.1.1"
reorderable = "2.1.1"
stately = "2.0.7"
sqlcipher = "4.6.0"
sqldelight = "2.0.2"
turbine = "1.1.0"
voyager = "1.0.0"

android-targetSdk = "34"
android-minSdk = "26"

[libraries]

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-core = { module = "androidx.core:core", version.ref = "androidx-core" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "androidx-crypto" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splashscreen" }
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }

kamel = { module = "media.kamel:kamel-image", version.ref = "kamel" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }

multiplatform-markdown-renderer = { module = "com.mikepenz:multiplatform-markdown-renderer", version.ref = "multiplatform-markdown-renderer" }
multiplatform-markdown-renderer-m3 = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "multiplatform-markdown-renderer" }
multiplatform-markdown-renderer-coil2 = { module = "com.mikepenz:multiplatform-markdown-renderer-coil2", version.ref = "multiplatform-markdown-renderer" }

multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorfit-ksp = { module = "de.jensklingenberg.ktorfit:ktorfit-ksp", version.ref = "ktorfit" }
ktorfit-lib = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" }

materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }

lyricist = { module = "cafe.adriel.lyricist:lyricist", version.ref = "lyricist" }

voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-screenmodel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
voyager-bottomsheet = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyager" }
voyager-tab = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
voyager-transition = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }

stately-common = { module = "co.touchlab:stately-common", version.ref = "stately" }

sqlcipher = { module = "net.zetetic:sqlcipher-android", version.ref = "sqlcipher" }
sqldelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }

kotlincrypto-bom = { module = "org.kotlincrypto.hash:bom", version.ref = "kotlincrypto" }
kotlincrypto-md5 = { module = "org.kotlincrypto.hash:md" }

exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidx-media3" }
exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "androidx-media3" }
exoplayer-ui = { module = "androidx.media3:media3-ui", version.ref = "androidx-media3" }

reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]

android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
