[versions]
androidx_activity_compose = "1.7.2"
android_gradle = "7.4.2"
compose = "1.4.3"
koin = "3.2.0"
kotlin = "1.8.22"
material3 = "1.1.1"

[libraries]

androidx_activity_compose = { module = "androidx.activity:activity-compose", version.ref = "androidx.activity.compose" }

compose_ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose_tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose_preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose_foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }

koin_core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin_test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin_android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
material3_windowsize = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }

[plugins]

android_application = { id = "com.android.application", version.ref = "android.gradle" }
android_library = { id = "com.android.library", version.ref = "android.gradle" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin_multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }