[versions]

androidx_activity = "1.8.2"
androidx_crypto = "1.0.0"
androidx_media3 = "1.2.0"
androidx_splashscreen = "1.0.1"
android_gif_drawable = "1.2.28"
android_gradle = "8.2.2"
coil = "2.5.0"
compose = "1.5.12"
compose_compiler = "1.5.8"
crashkios = "0.8.5"
crashlytics = "18.6.1"
crashlytics_gradle = "2.9.9"
gms_gradle = "4.4.0"
kamel = "0.9.1"
koin = "3.5.3"
kotlin = "1.9.22"
kotlincrypto = "0.3.0"
kotlinx_coroutines = "1.7.3"
kotlinx_serialization_json = "1.6.2"
ksp = "1.9.22-1.0.17"
ktor = "2.3.7"
ktorfit_gradle = "1.11.0"
ktorfit_lib = "1.11.0"
markdown = "0.5.0"
markwon = "4.6.2"
materialKolor = "1.3.0"
moko_resources = "0.23.0"
multiplatform_settings = "1.1.1"
sqlcipher = "4.5.5"
sqldelight = "2.0.1"
voyager = "1.0.0"

android_targetSdk = "34"
android_minSdk = "26"

[libraries]

androidx_activity_compose = { module = "androidx.activity:activity-compose", version.ref = "androidx.activity" }
androidx_activity = { module = "androidx.activity:activity", version.ref = "androidx.activity" }
androidx_security_crypto = { module = "androidx.security:security-crypto", version.ref = "androidx.crypto" }
androidx_splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx.splashscreen" }

kamel = { module = "media.kamel:kamel-image", version.ref = "kamel" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil_compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil_gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
android_gif_drawable = { module = "pl.droidsonroids.gif:android-gif-drawable", version.ref = "android.gif.drawable" }

firebase_crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "crashlytics" }
crashkios = { module = "co.touchlab.crashkios:crashlytics", version.ref = "crashkios" }

markdown = { module = "org.jetbrains:markdown", version.ref = "markdown" }
markwon_core = { module = "io.noties.markwon:core", version.ref = "markwon" }
markwon_strikethrough = { module = "io.noties.markwon:ext-strikethrough", version.ref = "markwon" }
markwon_tables = { module = "io.noties.markwon:ext-tables", version.ref = "markwon" }
markwon_html = { module = "io.noties.markwon:html", version.ref = "markwon" }
markwon_linkify = { module = "io.noties.markwon:linkify", version.ref = "markwon" }
markwon_image_coil = { module = "io.noties.markwon:image-coil", version.ref = "markwon" }

multiplatform_settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform.settings" }

kotlinx_serialization_json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx.serialization.json" }
kotlinx_coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx.coroutines" }

koin_core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin_test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin_android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

ktor_serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor_cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor_android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor_contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor_logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor_json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorfit_ksp = { module = "de.jensklingenberg.ktorfit:ktorfit-ksp", version.ref = "ktorfit.lib" }
ktorfit_lib = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit.lib" }

materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }

moko_gradle = { module = "dev.icerock.moko:resources-generator", version.ref = "moko.resources" }
moko_resources = { module = "dev.icerock.moko:resources", version.ref = "moko.resources" }
moko_resources_compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko.resources" }
moko_resources_test = { module = "dev.icerock.moko:resources-test", version.ref = "moko.resources" }

voyager_navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager_screenmodel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
voyager_bottomsheet = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyager" }
voyager_tab = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
voyager_transition = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager_koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }
voyager_androidx = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }

sqlcipher = { module = "net.zetetic:sqlcipher-android", version.ref = "sqlcipher" }
sqldelight_android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight_native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }

kotlincrypto_bom = { module = "org.kotlincrypto.hash:bom", version.ref = "kotlincrypto" }
kotlincrypto_md5 = { module = "org.kotlincrypto.hash:md" }

exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidx.media3" }
exoplayer_dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "androidx.media3" }
exoplayer_ui = { module = "androidx.media3:media3-ui", version.ref = "androidx.media3" }

[plugins]

android_application = { id = "com.android.application", version.ref = "android.gradle" }
android_library = { id = "com.android.library", version.ref = "android.gradle" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin_multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit.gradle" }
moko_resources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko.resources" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics.gradle" }
gms = { id = "com.google.gms.google-services", version.ref = "gms.gradle" }
