package com.livefast.eattrash.raccoonforlemmy.core.persistence.dao

import app.cash.sqldelight.Query
import com.livefast.eattrash.raccoonforlemmy.core.persistence.SettingsQueries
import com.livefast.eattrash.raccoonforlemmy.core.persistence.settings.GetBy

internal class DefaultSettingsDao(
    private val queries: SettingsQueries,
) : SettingsDao {
    override fun getBy(accountId: Long?): Query<GetBy> {
        return queries.getBy(accountId)
    }

    override fun create(
        theme: Long?,
        uiFontScale: Double,
        uiFontFamily: Long,
        titleFontScale: Double,
        contentFontScale: Double,
        commentFontScale: Double,
        ancillaryFontScale: Double,
        locale: String?,
        defaultListingType: Long,
        defaultPostSortType: Long,
        defaultCommentSortType: Long,
        defaultInboxType: Long,
        includeNsfw: Long,
        blurNsfw: Long,
        navigationTitlesVisible: Long,
        dynamicColors: Long,
        openUrlsInExternalBrowser: Long,
        enableSwipeActions: Long,
        enableDoubleTapAction: Long,
        customSeedColor: Long?,
        postLayout: Long,
        separateUpAndDownVotes: Long,
        autoLoadImages: Long,
        autoExpandComments: Long,
        fullHeightImages: Long,
        upvoteColor: Long?,
        downvoteColor: Long?,
        hideNavigationBarWhileScrolling: Long,
        zombieModeInterval: Long,
        zombieModeScrollAmount: Double,
        markAsReadWhileScrolling: Long,
        commentBarTheme: Long,
        replyColor: Long?,
        saveColor: Long?,
        searchPostTitleOnly: Long,
        contentFontFamily: Long,
        edgeToEdge: Long,
        postBodyMaxLines: Long?,
        infiniteScrollEnabled: Long,
        actionsOnSwipeToStartPosts: String?,
        actionsOnSwipeToEndPosts: String?,
        actionsOnSwipeToStartComments: String?,
        actionsOnSwipeToEndComments: String?,
        actionsOnSwipeToStartInbox: String?,
        actionsOnSwipeToEndInbox: String?,
        opaqueSystemBars: Long?,
        showScores: Long,
        preferUserNicknames: Long,
        commentBarThickness: Long,
        imageSourcePath: Long,
        defaultExploreType: Long,
        defaultLanguageId: Long?,
        inboxBackgroundCheckPeriod: Long?,
        fadeReadPosts: Long,
        showUnreadComments: Long,
        enableButtonsToScrollBetweenComments: Long,
        fullWidthImages: Long,
        commentIndentAmount: Long,
        enableToggleFavoriteInNavDrawer: Long,
        inboxPreviewMaxLines: Long?,
        defaultExploreResultType: Long,
        useAvatarAsProfileNavigationIcon: Long,
        randomThemeColor: Long,
        openPostWebPageOnImageClick: Long,
        accountId: Long?,
        restrictLocalUserSearch: Long,
        markAsReadOnInteraction: Long
    ) {
        queries.create(
            theme = theme,
            uiFontScale = uiFontScale,
            uiFontFamily = uiFontFamily,
            titleFontScale = titleFontScale,
            contentFontScale = contentFontScale,
            commentFontScale = commentFontScale,
            ancillaryFontScale = ancillaryFontScale,
            locale = locale,
            defaultListingType = defaultListingType,
            defaultPostSortType = defaultPostSortType,
            defaultCommentSortType = defaultCommentSortType,
            defaultInboxType = defaultInboxType,
            includeNsfw = includeNsfw,
            blurNsfw = blurNsfw,
            navigationTitlesVisible = navigationTitlesVisible,
            dynamicColors = dynamicColors,
            openUrlsInExternalBrowser = openUrlsInExternalBrowser,
            enableSwipeActions = enableSwipeActions,
            enableDoubleTapAction = enableDoubleTapAction,
            customSeedColor = customSeedColor,
            postLayout = postLayout,
            separateUpAndDownVotes = separateUpAndDownVotes,
            autoLoadImages = autoLoadImages,
            autoExpandComments = autoExpandComments,
            fullHeightImages = fullHeightImages,
            upvoteColor = upvoteColor,
            downvoteColor = downvoteColor,
            hideNavigationBarWhileScrolling = hideNavigationBarWhileScrolling,
            zombieModeInterval = zombieModeInterval,
            zombieModeScrollAmount = zombieModeScrollAmount,
            markAsReadWhileScrolling = markAsReadWhileScrolling,
            commentBarTheme = commentBarTheme,
            replyColor = replyColor,
            saveColor = saveColor,
            searchPostTitleOnly = searchPostTitleOnly,
            contentFontFamily = contentFontFamily,
            edgeToEdge = edgeToEdge,
            postBodyMaxLines = postBodyMaxLines,
            infiniteScrollEnabled = infiniteScrollEnabled,
            actionsOnSwipeToStartPosts = actionsOnSwipeToStartPosts,
            actionsOnSwipeToEndPosts = actionsOnSwipeToEndPosts,
            actionsOnSwipeToStartComments = actionsOnSwipeToStartComments,
            actionsOnSwipeToEndComments = actionsOnSwipeToEndComments,
            actionsOnSwipeToStartInbox = actionsOnSwipeToStartInbox,
            actionsOnSwipeToEndInbox = actionsOnSwipeToEndInbox,
            opaqueSystemBars = opaqueSystemBars,
            showScores = showScores,
            preferUserNicknames = preferUserNicknames,
            commentBarThickness = commentBarThickness,
            imageSourcePath = imageSourcePath,
            defaultExploreType = defaultExploreType,
            defaultLanguageId = defaultLanguageId,
            inboxBackgroundCheckPeriod = inboxBackgroundCheckPeriod,
            fadeReadPosts = fadeReadPosts,
            showUnreadComments = showUnreadComments,
            enableButtonsToScrollBetweenComments = enableButtonsToScrollBetweenComments,
            fullWidthImages = fullWidthImages,
            commentIndentAmount = commentIndentAmount,
            enableToggleFavoriteInNavDrawer = enableToggleFavoriteInNavDrawer,
            inboxPreviewMaxLines = inboxPreviewMaxLines,
            defaultExploreResultType = defaultExploreResultType,
            useAvatarAsProfileNavigationIcon = useAvatarAsProfileNavigationIcon,
            randomThemeColor = randomThemeColor,
            openPostWebPageOnImageClick = openPostWebPageOnImageClick,
            account_id = accountId,
            restrictLocalUserSearch = restrictLocalUserSearch,
            markAsReadOnInteraction = markAsReadOnInteraction,
        )
    }

    override fun update(
        theme: Long?,
        uiFontScale: Double,
        uiFontFamily: Long,
        titleFontScale: Double,
        contentFontScale: Double,
        commentFontScale: Double,
        ancillaryFontScale: Double,
        locale: String?,
        defaultListingType: Long,
        defaultPostSortType: Long,
        defaultCommentSortType: Long,
        defaultInboxType: Long,
        includeNsfw: Long,
        blurNsfw: Long,
        navigationTitlesVisible: Long,
        dynamicColors: Long,
        openUrlsInExternalBrowser: Long,
        enableSwipeActions: Long,
        enableDoubleTapAction: Long,
        customSeedColor: Long?,
        postLayout: Long,
        separateUpAndDownVotes: Long,
        autoLoadImages: Long,
        autoExpandComments: Long,
        fullHeightImages: Long,
        upvoteColor: Long?,
        downvoteColor: Long?,
        hideNavigationBarWhileScrolling: Long,
        zombieModeInterval: Long,
        zombieModeScrollAmount: Double,
        markAsReadWhileScrolling: Long,
        commentBarTheme: Long,
        replyColor: Long?,
        saveColor: Long?,
        searchPostTitleOnly: Long,
        contentFontFamily: Long,
        edgeToEdge: Long,
        postBodyMaxLines: Long?,
        infiniteScrollEnabled: Long,
        actionsOnSwipeToStartPosts: String?,
        actionsOnSwipeToEndPosts: String?,
        actionsOnSwipeToStartComments: String?,
        actionsOnSwipeToEndComments: String?,
        actionsOnSwipeToStartInbox: String?,
        actionsOnSwipeToEndInbox: String?,
        opaqueSystemBars: Long?,
        showScores: Long,
        preferUserNicknames: Long,
        commentBarThickness: Long,
        imageSourcePath: Long,
        defaultExploreType: Long,
        defaultLanguageId: Long?,
        inboxBackgroundCheckPeriod: Long?,
        fadeReadPosts: Long,
        showUnreadComments: Long,
        enableButtonsToScrollBetweenComments: Long,
        fullWidthImages: Long,
        commentIndentAmount: Long,
        enableToggleFavoriteInNavDrawer: Long,
        inboxPreviewMaxLines: Long?,
        defaultExploreResultType: Long,
        useAvatarAsProfileNavigationIcon: Long,
        randomThemeColor: Long,
        openPostWebPageOnImageClick: Long,
        restrictLocalUserSearch: Long,
        markAsReadOnInteraction: Long,
        accountId: Long?
    ) {
        queries.update(
            theme = theme,
            uiFontScale = uiFontScale,
            uiFontFamily = uiFontFamily,
            titleFontScale = titleFontScale,
            contentFontScale = contentFontScale,
            commentFontScale = commentFontScale,
            ancillaryFontScale = ancillaryFontScale,
            locale = locale,
            defaultListingType = defaultListingType,
            defaultPostSortType = defaultPostSortType,
            defaultCommentSortType = defaultCommentSortType,
            defaultInboxType = defaultInboxType,
            includeNsfw = includeNsfw,
            blurNsfw = blurNsfw,
            navigationTitlesVisible = navigationTitlesVisible,
            dynamicColors = dynamicColors,
            openUrlsInExternalBrowser = openUrlsInExternalBrowser,
            enableSwipeActions = enableSwipeActions,
            enableDoubleTapAction = enableDoubleTapAction,
            customSeedColor = customSeedColor,
            postLayout = postLayout,
            separateUpAndDownVotes = separateUpAndDownVotes,
            autoLoadImages = autoLoadImages,
            autoExpandComments = autoExpandComments,
            fullHeightImages = fullHeightImages,
            upvoteColor = upvoteColor,
            downvoteColor = downvoteColor,
            hideNavigationBarWhileScrolling = hideNavigationBarWhileScrolling,
            zombieModeInterval = zombieModeInterval,
            zombieModeScrollAmount = zombieModeScrollAmount,
            markAsReadWhileScrolling = markAsReadWhileScrolling,
            commentBarTheme = commentBarTheme,
            replyColor = replyColor,
            saveColor = saveColor,
            searchPostTitleOnly = searchPostTitleOnly,
            contentFontFamily = contentFontFamily,
            edgeToEdge = edgeToEdge,
            postBodyMaxLines = postBodyMaxLines,
            infiniteScrollEnabled = infiniteScrollEnabled,
            actionsOnSwipeToStartPosts = actionsOnSwipeToStartPosts,
            actionsOnSwipeToEndPosts = actionsOnSwipeToEndPosts,
            actionsOnSwipeToStartComments = actionsOnSwipeToStartComments,
            actionsOnSwipeToEndComments = actionsOnSwipeToEndComments,
            actionsOnSwipeToStartInbox = actionsOnSwipeToStartInbox,
            actionsOnSwipeToEndInbox = actionsOnSwipeToEndInbox,
            opaqueSystemBars = opaqueSystemBars,
            showScores = showScores,
            preferUserNicknames = preferUserNicknames,
            commentBarThickness = commentBarThickness,
            imageSourcePath = imageSourcePath,
            defaultExploreType = defaultExploreType,
            defaultLanguageId = defaultLanguageId,
            inboxBackgroundCheckPeriod = inboxBackgroundCheckPeriod,
            fadeReadPosts = fadeReadPosts,
            showUnreadComments = showUnreadComments,
            enableButtonsToScrollBetweenComments = enableButtonsToScrollBetweenComments,
            fullWidthImages = fullWidthImages,
            commentIndentAmount = commentIndentAmount,
            enableToggleFavoriteInNavDrawer = enableToggleFavoriteInNavDrawer,
            inboxPreviewMaxLines = inboxPreviewMaxLines,
            defaultExploreResultType = defaultExploreResultType,
            useAvatarAsProfileNavigationIcon = useAvatarAsProfileNavigationIcon,
            randomThemeColor = randomThemeColor,
            openPostWebPageOnImageClick = openPostWebPageOnImageClick,
            restrictLocalUserSearch = restrictLocalUserSearch,
            markAsReadOnInteraction = markAsReadOnInteraction,
            account_id = accountId,
        )
    }
}
