package com.github.diegoberaldin.raccoonforlemmy.core.notifications

object NotificationCenterContractKeys {
    const val ChangeSortType = "changeSortType"
    const val ChangeCommentSortType = "changeCommentSortType"
    const val ChangeFeedType = "changeFeedType"
    const val ChangeInboxType = "changeInboxType"
    const val ChangeTheme = "changeTheme"
    const val ChangeContentFontSize = "changeContentFontSize"
    const val ChangeUiFontSize = "changeUiFontSize"
    const val ChangeFontFamily = "changeFontFamily"
    const val ChangeZombieInterval = "changeZombieInterval"
    const val ChangeLanguage = "changeLanguage"
    const val ChangePostLayout = "changePostLayout"
    const val Logout = "logout"
    const val PostCreated = "postCreated"
    const val CommentCreated = "commentCreated"
    const val PostUpdated = "postUpdated"
    const val PostDeleted = "postDeleted"
    const val ChangeColor = "changeColor"
    const val ChangeZombieScrollAmount = "changeZombieScrollAmount"
    const val MultiCommunityCreated = "multiCommunityCreated"
    const val ResetContents = "resetContents"
    const val CloseDialog = "closeDialog"
}