package com.livefast.eattrash.raccoonforlemmy.core.resources.testutils

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.painter.ColorPainter
import androidx.compose.ui.graphics.painter.Painter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import chaintech.videoplayer.model.VideoPlayerConfig
import com.livefast.eattrash.raccoonforlemmy.core.resources.CoreResources

private val mockPainter = ColorPainter(Color.Transparent)
private val mockImageVector = ImageVector.Builder(
    name = "Mock",
    defaultWidth = 24.dp,
    defaultHeight = 24.dp,
    viewportWidth = 24f,
    viewportHeight = 24f,
).build()

object MockResources : CoreResources {
    override val atkinsonHyperlegible: FontFamily
        @Composable get() = FontFamily.Default
    override val poppins: FontFamily
        @Composable get() = FontFamily.Default
    override val notoSans: FontFamily
        @Composable get() = FontFamily.Default

    override val appIconDefault: Painter
        @Composable get() = mockPainter
    override val github: Painter
        @Composable get() = mockPainter
    override val lemmy: Painter
        @Composable get() = mockPainter
    override val appIconClassical: Painter
        @Composable get() = mockPainter


    override val videoPlayerConfig: VideoPlayerConfig = VideoPlayerConfig()

    override val abc: ImageVector
        @Composable get() = mockImageVector
    override val accountCircleFill: ImageVector
        @Composable get() = mockImageVector
    override val add: ImageVector
        @Composable get() = mockImageVector
    override val addCircle: ImageVector
        @Composable get() = mockImageVector
    override val adminPanelSettings: ImageVector
        @Composable get() = mockImageVector
    override val allInclusive: ImageVector
        @Composable get() = mockImageVector
    override val alternateEmail: ImageVector
        @Composable get() = mockImageVector
    override val api: ImageVector
        @Composable get() = mockImageVector
    override val arrowBack: ImageVector
        @Composable get() = mockImageVector
    override val arrowCircleDown: ImageVector
        @Composable get() = mockImageVector
    override val arrowCircleUp: ImageVector
        @Composable get() = mockImageVector
    override val arrowDropDown: ImageVector
        @Composable get() = mockImageVector
    override val article: ImageVector
        @Composable get() = mockImageVector
    override val aspectRatio: ImageVector
        @Composable get() = mockImageVector
    override val awardStar: ImageVector
        @Composable get() = mockImageVector
    override val book: ImageVector
        @Composable get() = mockImageVector
    override val bookmark: ImageVector
        @Composable get() = mockImageVector
    override val bookmarksFill: ImageVector
        @Composable get() = mockImageVector
    override val bookmarkFill: ImageVector
        @Composable get() = mockImageVector
    override val bugReport: ImageVector
        @Composable get() = mockImageVector
    override val cake: ImageVector
        @Composable get() = mockImageVector
    override val calendarMonthFill: ImageVector
        @Composable get() = mockImageVector
    override val calendarViewDayFill: ImageVector
        @Composable get() = mockImageVector
    override val camera: ImageVector
        @Composable get() = mockImageVector
    override val cancel: ImageVector
        @Composable get() = mockImageVector
    override val changeCircle: ImageVector
        @Composable get() = mockImageVector
    override val chatFill: ImageVector
        @Composable get() = mockImageVector
    override val check: ImageVector
        @Composable get() = mockImageVector
    override val checkCircle: ImageVector
        @Composable get() = mockImageVector
    override val chevronForward: ImageVector
        @Composable get() = mockImageVector
    override val circle: ImageVector
        @Composable get() = mockImageVector
    override val code: ImageVector
        @Composable get() = mockImageVector
    override val clearAll: ImageVector
        @Composable get() = mockImageVector
    override val close: ImageVector
        @Composable get() = mockImageVector
    override val comment: ImageVector
        @Composable get() = mockImageVector
    override val computer: ImageVector
        @Composable get() = mockImageVector
    override val cottage: ImageVector
        @Composable get() = mockImageVector
    override val darkMode: ImageVector
        @Composable get() = mockImageVector
    override val darkModeFill: ImageVector
        @Composable get() = mockImageVector
    override val displaySettings: ImageVector
        @Composable get() = mockImageVector
    override val doneAll: ImageVector
        @Composable get() = mockImageVector
    override val doNotDisturbOn: ImageVector
        @Composable get() = mockImageVector
    override val download: ImageVector
        @Composable get() = mockImageVector
    override val edit: ImageVector
        @Composable get() = mockImageVector
    override val elderlyWoman: ImageVector
        @Composable get() = mockImageVector
    override val explicitFill: ImageVector
        @Composable get() = mockImageVector
    override val exploreFill: ImageVector
        @Composable get() = mockImageVector
    override val favorite: ImageVector
        @Composable get() = mockImageVector
    override val fileOpen: ImageVector
        @Composable get() = mockImageVector
    override val formatBold: ImageVector
        @Composable get() = mockImageVector
    override val formatItalic: ImageVector
        @Composable get() = mockImageVector
    override val formatListBulleted: ImageVector
        @Composable get() = mockImageVector
    override val formatListNumbered: ImageVector
        @Composable get() = mockImageVector
    override val formatQuote: ImageVector
        @Composable get() = mockImageVector
    override val gavel: ImageVector
        @Composable get() = mockImageVector
    override val group: ImageVector
        @Composable get() = mockImageVector
    override val groups: ImageVector
        @Composable get() = mockImageVector
    override val homeFill: ImageVector
        @Composable get() = mockImageVector
    override val image: ImageVector
        @Composable get() = mockImageVector
    override val inboxFill: ImageVector
        @Composable get() = mockImageVector
    override val info: ImageVector
        @Composable get() = mockImageVector
    override val keyboardArrowDown: ImageVector
        @Composable get() = mockImageVector
    override val keyboardArrowLeft: ImageVector
        @Composable get() = mockImageVector
    override val keyboardArrowRight: ImageVector
        @Composable get() = mockImageVector
    override val keyboardArrowUp: ImageVector
        @Composable get() = mockImageVector
    override val keyboardDoubleArrowLeft: ImageVector
        @Composable get() = mockImageVector
    override val keyboardDoubleArrowRight: ImageVector
        @Composable get() = mockImageVector
    override val lightMode: ImageVector
        @Composable get() = mockImageVector
    override val link: ImageVector
        @Composable get() = mockImageVector
    override val listAlt: ImageVector
        @Composable get() = mockImageVector
    override val localFireDepartment: ImageVector
        @Composable get() = mockImageVector
    override val localPolice: ImageVector
        @Composable get() = mockImageVector
    override val lock: ImageVector
        @Composable get() = mockImageVector
    override val logout: ImageVector
        @Composable get() = mockImageVector
    override val markChatRead: ImageVector
        @Composable get() = mockImageVector
    override val markChatUnread: ImageVector
        @Composable get() = mockImageVector
    override val menu: ImageVector
        @Composable get() = mockImageVector
    override val menuOpen: ImageVector
        @Composable get() = mockImageVector
    override val moreHoriz: ImageVector
        @Composable get() = mockImageVector
    override val moreVert: ImageVector
        @Composable get() = mockImageVector
    override val notifications: ImageVector
        @Composable get() = mockImageVector
    override val openInBrowser: ImageVector
        @Composable get() = mockImageVector
    override val palette: ImageVector
        @Composable get() = mockImageVector
    override val pending: ImageVector
        @Composable get() = mockImageVector
    override val percent: ImageVector
        @Composable get() = mockImageVector
    override val person: ImageVector
        @Composable get() = mockImageVector
    override val playCircle: ImageVector
        @Composable get() = mockImageVector
    override val preview: ImageVector
        @Composable get() = mockImageVector
    override val public: ImageVector
        @Composable get() = mockImageVector
    override val reply: ImageVector
        @Composable get() = mockImageVector
    override val report: ImageVector
        @Composable get() = mockImageVector
    override val reportOff: ImageVector
        @Composable get() = mockImageVector
    override val rocketLaunch: ImageVector
        @Composable get() = mockImageVector
    override val save: ImageVector
        @Composable get() = mockImageVector
    override val scale: ImageVector
        @Composable get() = mockImageVector
    override val science: ImageVector
        @Composable get() = mockImageVector
    override val schedule: ImageVector
        @Composable get() = mockImageVector
    override val share: ImageVector
        @Composable get() = mockImageVector
    override val search: ImageVector
        @Composable get() = mockImageVector
    override val send: ImageVector
        @Composable get() = mockImageVector
    override val settingsApplications: ImageVector
        @Composable get() = mockImageVector
    override val settingsFill: ImageVector
        @Composable get() = mockImageVector
    override val shield: ImageVector
        @Composable get() = mockImageVector
    override val star: ImageVector
        @Composable get() = mockImageVector
    override val starFill: ImageVector
        @Composable get() = mockImageVector
    override val strikethroughS: ImageVector
        @Composable get() = mockImageVector
    override val styleFill: ImageVector
        @Composable get() = mockImageVector
    override val stylusFountainPenFill: ImageVector
        @Composable get() = mockImageVector
    override val sync: ImageVector
        @Composable get() = mockImageVector
    override val syncDisabled: ImageVector
        @Composable get() = mockImageVector
    override val support: ImageVector
        @Composable get() = mockImageVector
    override val tag: ImageVector
        @Composable get() = mockImageVector
    override val thumbsUpDownFill: ImageVector
        @Composable get() = mockImageVector
    override val thunderstorm: ImageVector
        @Composable get() = mockImageVector
    override val trendingUp: ImageVector
        @Composable get() = mockImageVector
    override val unfoldLess: ImageVector
        @Composable get() = mockImageVector
    override val unfoldMore: ImageVector
        @Composable get() = mockImageVector
    override val update: ImageVector
        @Composable get() = mockImageVector
    override val viewWeekFill: ImageVector
        @Composable get() = mockImageVector
    override val verified: ImageVector
        @Composable get() = mockImageVector
    override val visibility: ImageVector
        @Composable get() = mockImageVector
    override val visibilityOff: ImageVector
        @Composable get() = mockImageVector
    override val volunteerActivism: ImageVector
        @Composable get() = mockImageVector
    override val workspacePremium: ImageVector
        @Composable get() = mockImageVector
}
